# Generated by Django 5.0.3 on 2024-05-03 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDoctor', models.IntegerField(blank=True, null=True)),
                ('doctorName', models.TextField(blank=True, default='', max_length=100, verbose_name='Adı:')),
                ('doctorLastName', models.TextField(blank=True, default='', max_length=100, verbose_name='Soyadı:')),
                ('uzmanlikAlani', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Uzmanlık Alanı')),
                ('calismaYeri', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Çalıştığı Hastane')),
            ],
        ),
        migrations.CreateModel(
            name='Hasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHasta', models.IntegerField(blank=True, null=True)),
                ('hastaAdi', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Hasta Adı')),
                ('hastaSoyadi', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Hasta Soyadı')),
                ('dogumTarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('cinsiyet', models.CharField(blank=True, default='', max_length=1, verbose_name='Cinsiyeti')),
                ('telefonNo', models.TextField(blank=True, default='', max_length=10, null=True, verbose_name='Telefon Numarası')),
                ('adres', models.TextField(max_length=3000, verbose_name='Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Yonetici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idYonetici', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRandevu', models.IntegerField(blank=True, null=True)),
                ('randevuTarihi', models.DateField(blank=True, null=True, verbose_name='Randevu Tarihi')),
                ('randevuSaati', models.DateTimeField(blank=True, null=True, verbose_name='Randevu Saati')),
                ('idDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HastaneUyg.doctor')),
                ('idHasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HastaneUyg.hasta')),
            ],
        ),
        migrations.CreateModel(
            name='TibbiRaporlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRapor', models.IntegerField(blank=True, null=True)),
                ('raporTarihi', models.DateField(blank=True, null=True, verbose_name='Rapor Tarihi')),
                ('uzmanlikAlani', models.TextField(blank=True, default='', max_length=120, null=True, verbose_name='Uzmanlık Alanı')),
                ('raporIcerigi', models.TextField(blank=True, default='', max_length=4000)),
                ('idDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HastaneUyg.doctor')),
                ('idHasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HastaneUyg.hasta')),
            ],
        ),
    ]
