# Generated by Django 5.0.3 on 2024-05-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HastaneUyg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctorName',
            new_name='AD',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='calismaYeri',
            new_name='CalismaYeri',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctorLastName',
            new_name='SOYAD',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='uzmanlikAlani',
            new_name='UzmanlikAlani',
        ),
    ]
