# Generated by Django 5.0.3 on 2024-05-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HastaneUyg', '0002_rename_doctorname_doctor_ad_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='doktorlar',
        ),
    ]
