# Generated by Django 5.0.3 on 2024-05-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HastaneUyg', '0003_alter_doctor_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='idDoctor',
            field=models.TextField(blank=True, default='', max_length=11, primary_key=True, serialize=False, verbose_name="Doktor ID'si"),
        ),
    ]
