# Generated by Django 5.0.3 on 2024-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HastaneUyg', '0004_remove_doctor_id_alter_doctor_iddoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='idDoctor',
            field=models.BigIntegerField(blank=True, default='', primary_key=True, serialize=False, verbose_name="Doktor ID'si"),
        ),
    ]
