# Generated by Django 5.0.3 on 2024-05-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HastaneUyg', '0005_alter_doctor_iddoctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevu',
            name='idRandevu',
        ),
        migrations.AlterModelTable(
            name='hasta',
            table='hastalar',
        ),
        migrations.AlterModelTable(
            name='randevu',
            table='randevular',
        ),
        migrations.AlterModelTable(
            name='tibbiraporlar',
            table='tibbiraporlar',
        ),
        migrations.AlterModelTable(
            name='yonetici',
            table='yonetici',
        ),
    ]
