# Generated by Django 5.0.3 on 2024-05-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HastaneUyg', '0006_remove_randevu_idrandevu_alter_hasta_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='idRandevu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
