# Generated by Django 5.0.3 on 2024-05-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HastaneUyg', '0008_alter_doctor_table_alter_hasta_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='doktorlar',
        ),
        migrations.AlterModelTable(
            name='hasta',
            table='hastalar',
        ),
        migrations.AlterModelTable(
            name='randevu',
            table='randevular',
        ),
        migrations.AlterModelTable(
            name='tibbiraporlar',
            table='tibbiraporlar',
        ),
        migrations.AlterModelTable(
            name='yonetici',
            table='yonetici',
        ),
    ]
