# Generated by Django 5.0.3 on 2024-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HastaneUyg', '0009_alter_doctor_table_alter_hasta_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevu',
            name='id',
        ),
        migrations.RemoveField(
            model_name='randevu',
            name='idDoctor',
        ),
        migrations.RemoveField(
            model_name='randevu',
            name='idHasta',
        ),
        migrations.RemoveField(
            model_name='randevu',
            name='idRandevu',
        ),
        migrations.RemoveField(
            model_name='randevu',
            name='randevuSaati',
        ),
        migrations.RemoveField(
            model_name='tibbiraporlar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tibbiraporlar',
            name='idDoctor',
        ),
        migrations.RemoveField(
            model_name='tibbiraporlar',
            name='idHasta',
        ),
        migrations.RemoveField(
            model_name='tibbiraporlar',
            name='raporIcerigi',
        ),
        migrations.AddField(
            model_name='randevu',
            name='doktor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='randevu',
            name='hasta_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='randevu',
            name='randevuId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='randevu',
            name='randevu_saati',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Randevu Saati'),
        ),
        migrations.AddField(
            model_name='tibbiraporlar',
            name='doktor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tibbiraporlar',
            name='hasta_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tibbiraporlar',
            name='randevunun_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tibbiraporlar',
            name='rapor_icerigi',
            field=models.TextField(default='', max_length=3000, verbose_name='Rapor İçeriği'),
        ),
        migrations.AddField(
            model_name='tibbiraporlar',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='rapor_resimleri/'),
        ),
        migrations.AlterField(
            model_name='tibbiraporlar',
            name='idRapor',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
